### ISSUE TITLE
API is returning three incorrect attributes

### ISSUE THREAD

**Issue by nowyasimi** [nowyasimi/no8am#2]
API calls to endpoints that return section information give invalid data for `resSeats`, `prm`, and `CCC`. For example, https://no8.am/course/CSCI/203 returns:

```
{
  "cache_time": 1486619188,
  "sections": {
    "52347": {
      "CCC": "Desc",
      "CRN": "52347",
      "bare_course_number": "CSCI 203",
      "courseName": "Intro to Computer Science I",
      "courseNum": "CSCI 203 02",
      "course_number": "203",
      "department": "CSCI",
      "extra_section_independent": {... },
      "extra_section_lists": { ...  },
      "freeSeats": "3",
      "main": true,
      "message": "Section CSCI 203 02: Students must also select a 203 lab section.",
      "prm": "FRST NMLG NSMC ",
      "professor": "Wittie, Lea",
      "resSeats": "",
      "roomMet": "BRKI 066",
      "sectionNum": "02",
      "timesMet": "MWF 2:00-2:52pm",
      "waitList": ""
      },
      ...
}
```

These three incorrect attributes correspond to the last three columns scraped from the Bucknell course information tables.

To get started on this issue, take a look at [scraper.py](https://github.com/nowyasimi/no8am/blob/master/no8am/scraper.py#L143).

**Comment by ymittal** [comment]
I might have figured out what's going wrong. Do the original web pages still have a `waitlist` column? I am quite certain that it used to be there, but now I am unable to find any search result with that column.

**Comment by nowyasimi** [comment]
Good catch! I wonder if the waitlist column will come back during course registration...

**Comment by ymittal** [comment]
That's what I was thinking. I am going to make a PR, check whenever you can.
