### ISSUE TITLE
Add a "Fork me on Github" ribbon to the homepage

### ISSUE THREAD

**Issue by nowyasimi** [nowyasimi/no8am#6]
Add a [ribbon](https://github.com/blog/273-github-ribbons) or something similar to the `index.html` template to let people know that no8am is now open source!

**Comment by TheAlbinoPanda** [comment]
Hey ! Is it ok if I help out with this ? I'm new to contributing to open source projects , so just let me know the best way to go about this !

**Comment by nowyasimi** [comment]
Yeah! Try to get the repo set up on your local machine using the instructions in the README. Then see if you can start up the server and make changes to `index.html`. Let me know if you run into any problems.
